index:
  name: generated_documentation_v0
  url: http://localhost:6333
  embedding_model:
    name: BAAI/llm-embedder
    dimensions: 768
    provider: hf
sources:
  default:
    engine: postgres
    user: ${env:POSTGRES_USER}
    password: ${env:POSTGRES_PASSWORD}
    host: ${env:POSTGRES_HOST}
    port: ${env:POSTGRES_PORT}
    dbname: ${env:POSTGRES_DATABASE}
internal_db:
  engine: duckdb
  path: /_internal/database.duckdb