index:
  name: generated_documentation_v0
  url: http://localhost:6333
  embedding_model:
    name: paraphrase-multilingual-mpnet-base-v2
    dimensions: 768
    provider: sf
sources:
  default:
    engine: postgres
    user: ${env:POSTGRES_USER}
    password: ${env:POSTGRES_PASSWORD}
    host: ${env:POSTGRES_HOST}
    port: ${env:POSTGRES_PORT}
    dbname: ${env:POSTGRES_DATABASE}
    schema_query_path: /core/sql/postgres.sql
internal_db:
  engine: duckdb
  path: /_internal/database.duckdb
llm:
  model: gemini
  provider: gemini/gemini-2.0-flash
  remote: true
  temperature: 0.4