index:
  name: generated_documentation_v0
  local: true
  url: /_internal/index
  embedding_model:
    name: paraphrase-multilingual-mpnet-base-v2
    dimensions: 768
    provider: sf
sources:
  default:
    engine: oracle
    user: ${env:FRAUD_USR}
    password: ${env:FRAUD_PASS}
    dsn: ${env:FRAUD_DSN}
    dbname: ${env:POSTGRES_DATABASE}
    schema_query_path: /core/sql/oracle.sql
internal_db:
  engine: duckdb
  path: /_internal/database.duckdb
  ddl_query_path: /core/sql/_internal_schema.sql
llm:
  provider: openai
  model: llama-3.3-70B
  remote: true
  base_url: http://10.235.0.23:8000/v1
  temperature: 0.4